--CUSTOMERS
INSERT INTO CUSTOMERS (CUSTOMERNAME, DESCRIPTION) VALUES ('Nasa','Space guys');
INSERT INTO CUSTOMERS (CUSTOMERNAME, DESCRIPTION) VALUES ('Deutsche bank','Bank of the bank');
INSERT INTO CUSTOMERS (CUSTOMERNAME, DESCRIPTION) VALUES ('Vatikan','Religion');
INSERT INTO CUSTOMERS (CUSTOMERNAME, DESCRIPTION) VALUES ('IBM','Not bad hardware');
INSERT INTO CUSTOMERS (CUSTOMERNAME, DESCRIPTION) VALUES ('Hewlett-Packard','Awesome hardware');
INSERT INTO CUSTOMERS (CUSTOMERNAME, DESCRIPTION) VALUES ('UBS','Opus Dei');
INSERT INTO CUSTOMERS (CUSTOMERNAME, DESCRIPTION) VALUES ('Amazon','Bookstore');
INSERT INTO CUSTOMERS (CUSTOMERNAME, DESCRIPTION) VALUES ('Thales','Army');
INSERT INTO CUSTOMERS (CUSTOMERNAME, DESCRIPTION) VALUES ('Amadeus','Travels');
INSERT INTO CUSTOMERS (CUSTOMERNAME, DESCRIPTION) VALUES ('Darth Vader','Boss');
INSERT INTO CUSTOMERS (CUSTOMERNAME, DESCRIPTION) VALUES ('Google','Services');
INSERT INTO CUSTOMERS (CUSTOMERNAME, DESCRIPTION) VALUES ('Avenir','Best developer I ever knew');
 
--GIFTS
INSERT INTO GIFTS (GIFTNAME,DESCRIPTION) VALUES ('Big Cookie','Big cookie with chocolate and little jellies');
INSERT INTO GIFTS (GIFTNAME,DESCRIPTION) VALUES ('Cool Gun','Shiny gun with red exploded bullets and laser.');
INSERT INTO GIFTS (GIFTNAME,DESCRIPTION) VALUES ('Book "Clean Code','Manual for good sleeping.');

--ORDERS---
INSERT INTO ORDERS (IDGIFT,IDCUSTOMER,ORDERCOUNT) VALUES ('1','2','3');
INSERT INTO ORDERS (IDGIFT,IDCUSTOMER,ORDERCOUNT) VALUES  ('3','2','1');
INSERT INTO ORDERS (IDGIFT,IDCUSTOMER,ORDERCOUNT) VALUES  ('2','3','1');
INSERT INTO ORDERS (IDGIFT,IDCUSTOMER,ORDERCOUNT) VALUES  ('1','3','2');